---
name: Create packages and test installation

on:
  pull_request:

jobs:
  # XXX done outside of the build matrix due to different container name
  build-centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y ginfo.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el7.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/noarch/ginfo-*.el7.noarch.rpm

  # Use a matrix for AlmaLinux versions
  build-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y ginfo.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el${{ matrix.almalinux-version }}.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/noarch/ginfo-*.el${{ matrix.almalinux-version }}.noarch.rpm

  # XXX: python3 comes from EPEL
  install-centos7:
    name: Install CentOS 7 RPMs
    needs: build-centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum localinstall -y ginfo-*.el7.noarch.rpm

  # Use a matrix for AlmaLinux versions
  install-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Install AlmaLinux ${{ matrix.almalinux-version }} RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
      - name: Install generated RPMs
        run: |
          yum localinstall -y ginfo-*.el${{ matrix.almalinux-version }}.noarch.rpm
