---
name: Run tests

on:
  pull_request:

jobs:
  # XXX only test on CentOS 7, due to dependencies not yet available
  test-centos7:
    name: Run tests on CentOS 7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          # Install requirements
          yum install -y yum-plugin-priorities
          yum install -y epel-release
          yum install -y http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
          yum install -y python3 bdii-config-site
          # to provide killall
          yum install -y psmisc
          cd tests/
          # Start Database
          ./run-db
          # Run the tests
          ./run-tests.sh
